In [5]:
import numpy as np
import math
from scipy.linalg import eig 

In [6]:
M = np.matrix('1 0 3; 3 7 2; 2 -2 8; 0 -1 1; 5 8 7')
MT = M.transpose()
MTM = np.dot(MT, M)
MMT = np.dot(M, MT)
print(M)
print(MT)
print(MTM)
print(MMT)
MTMe = eig(MTM)
print(MTMe)

[[ 1  0  3]
 [ 3  7  2]
 [ 2 -2  8]
 [ 0 -1  1]
 [ 5  8  7]]
[[ 1  3  2  0  5]
 [ 0  7 -2 -1  8]
 [ 3  2  8  1  7]]
[[ 39  57  60]
 [ 57 118  53]
 [ 60  53 127]]
[[ 10   9  26   3  26]
 [  9  62   8  -5  85]
 [ 26   8  72  10  50]
 [  3  -5  10   2  -1]
 [ 26  85  50  -1 138]]
(array([  2.14670489e+02+0.j,   9.32587341e-15+0.j,   6.93295108e+01+0.j]), array([[ 0.42615127,  0.90453403, -0.01460404],
       [ 0.61500884, -0.30151134, -0.72859799],
       [ 0.66344497, -0.30151134,  0.68478587]]))
