In [45]:
import numpy as np
from numpy import dot, diag, matrix
import math
from scipy.linalg import eig 

In [8]:
M = matrix('1 0 3; 3 7 2; 2 -2 8; 0 -1 1; 5 8 7')
MT = M.transpose()
MTM = dot(MT, M)
MMT = dot(M, MT)
print(M)
print(MT)
print(MTM)
print(MMT)
MTMe = eig(MTM)
MMTe = eig(MMT)
print(MTMe[0])
print(MTMe[1])
print(MMTe[0])
print(MMTe[1])

[[ 1  0  3]
 [ 3  7  2]
 [ 2 -2  8]
 [ 0 -1  1]
 [ 5  8  7]]
[[ 1  3  2  0  5]
 [ 0  7 -2 -1  8]
 [ 3  2  8  1  7]]
[[ 39  57  60]
 [ 57 118  53]
 [ 60  53 127]]
[[ 10   9  26   3  26]
 [  9  62   8  -5  85]
 [ 26   8  72  10  50]
 [  3  -5  10   2  -1]
 [ 26  85  50  -1 138]]
[  2.14670489e+02+0.j   9.32587341e-15+0.j   6.93295108e+01+0.j]
[[ 0.42615127  0.90453403 -0.01460404]
 [ 0.61500884 -0.30151134 -0.72859799]
 [ 0.66344497 -0.30151134  0.68478587]]
[  2.14670489e+02+0.j  -8.88178420e-16+0.j   6.93295108e+01+0.j
  -3.34838281e-15+0.j   7.47833227e-16+0.j]
[[-0.16492942 -0.95539856  0.24497323 -0.54001979 -0.78501713]
 [-0.47164732 -0.03481209 -0.45330644 -0.62022234  0.30294097]
 [-0.33647055  0.27076072  0.82943965 -0.12704172  0.2856551 ]
 [-0.00330585  0.04409532  0.16974659  0.16015949  0.43709105]
 [-0.79820031  0.10366268 -0.13310656  0.53095405 -0.13902319]]


In [ ]:
print(dot([[-0.16492942, -0.24497323,  0.9484818,   0.02118387, -0.11278259]
 [-0.47164732,  0.45330644 -0.05608348  0.10308932 -0.74718761]
 [-0.33647055 -0.82943965 -0.30370469 -0.15189627 -0.28897825]
 [-0.00330585 -0.16974659 -0.06169017  0.98276291  0.03932632]
 [-0.79820031  0.13310656 -0.0345644  -0.00533186  0.58646038]], [  1.46516378e+01,   8.32643446e+00, 0]))

In [35]:
from numpy.linalg import svd

u, sig, vt = svd(M)
print(u)
print(sig)
print(vt)

[[-0.16492942 -0.24497323  0.9484818   0.02118387 -0.11278259]
 [-0.47164732  0.45330644 -0.05608348  0.10308932 -0.74718761]
 [-0.33647055 -0.82943965 -0.30370469 -0.15189627 -0.28897825]
 [-0.00330585 -0.16974659 -0.06169017  0.98276291  0.03932632]
 [-0.79820031  0.13310656 -0.0345644  -0.00533186  0.58646038]]
[  1.46516378e+01   8.32643446e+00   1.73274791e-15]
[[-0.42615127 -0.61500884 -0.66344497]
 [ 0.01460404  0.72859799 -0.68478587]
 [-0.90453403  0.30151134  0.30151134]]


In [36]:
sig[2] = 0
print(sig)

[ 14.65163776   8.32643446   0.        ]


In [37]:
sig = diag(sig)
print(sig)

[[ 14.65163776   0.           0.        ]
 [  0.           8.32643446   0.        ]
 [  0.           0.           0.        ]]


In [38]:
sig = np.append(sig, [0,0,0])
sig = np.append(sig, [0,0,0])
print(sig)

[ 14.65163776   0.           0.           0.           8.32643446   0.           0.
   0.           0.           0.           0.           0.           0.           0.
   0.        ]


In [40]:
sig = sig.reshape(5,3)
print(sig)

[[ 14.65163776   0.           0.        ]
 [  0.           8.32643446   0.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]]


In [44]:

print(sig)
firstDot = dot(sig, vt)
newM = dot(u, firstDot)
print(newM)

[[ 14.65163776   0.           0.        ]
 [  0.           8.32643446   0.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]]
[[  1.00000000e+00   1.55431223e-15   3.00000000e+00]
 [  3.00000000e+00   7.00000000e+00   2.00000000e+00]
 [  2.00000000e+00  -2.00000000e+00   8.00000000e+00]
 [ -1.04083409e-16  -1.00000000e+00   1.00000000e+00]
 [  5.00000000e+00   8.00000000e+00   7.00000000e+00]]
